name: custom

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Custom parameter'
        default: 'master'
        required: true

jobs:
  custom:
    runs-on: ubuntu-latest

    steps:
      - name: Print Custom Parameter
        run: |
          echo "Custom parameter value: ${{ github.event.inputs.ref}}"
