name: custom

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Custom parameter'
        default: 'master'
        required: false
      buf:
        description: 'Custom parameter'
        default: 'tesst'
        required: false
      obj:
        type: choice
        description: 'Custom parameter'
       

jobs:
  custom:
    runs-on: ubuntu-latest

    steps:
      - name: Triggering Workflow for Issue Creation
        run: |
          echo "Custom parameter value: ${{ github.event.inputs.ref}}"
          echo "Custom parameter value: ${{ github.event.ref}}"
          echo "Custom parameter value: ${{ github.event.inputs.obj.one}}"
