name: List Open Issues

on:
  push:
    branches:
      - main

jobs:
  list-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Open Issues
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues?state=open"
          
          echo "Fetching open issues..."
          RESPONSE=$(curl -sSL -H "Authorization: token ${TOKEN}" "${API_URL}")
          echo "${RESPONSE}"
