name: Scheduled Workflow for Issue Tracker
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
jobs:
  IterateIssues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      - name: List Open Issues
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues?state=open"
          
          
          echo "Fetching open issues..."
          python -c "print('\n\n')"
          RESPONSE=$(curl -sSL -H "Authorization: token ${TOKEN}" "${API_URL}")
         
          for ISSUE in $(echo "${RESPONSE}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${ISSUE} | base64 --decode | jq -r ${1}
            }

            ISSUE_TITLE=$(_jq '.title')
            ISSUE_BODY=$(_jq '.body')
            ISSUE_USER=$(_jq '.user.login')
            UP_API_URL="https://api.github.com/users/${ISSUE_USER}"
            created_at=$(_jq '.created_at')
            updated_at=$(_jq '.updated_at')
            I_NUM=$(_jq '.number')
            current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            created=$(date -u -d "$created_at" +"%s")
            updated=$(date -u -d "$current_date" +"%s")

            time_difference=$((updated - created))

            hours=$((time_difference / 3600))
            minutes=$(( (time_difference % 3600) / 60 ))
            seconds=$((time_difference % 60))

            USER_DATA=$(curl -sSL -H "Authorization: token ${TOKEN}" "${UP_API_URL}")
            echo "${USER_DATA}" > user.json
            USER_EMAIL=$(jq -r '.email' user.json)
            MANAGER_LOGIN=$(jq -r '.manager_login' user.json)

            if [[ -z "${USER_EMAIL}" ]]; then
              echo "Email is Null Pelase configure your email id in your profile..!!!!!"
            else
              echo "Email id is ${USER_EMAIL}"
            fi

            echo "User's Manager Login: ${MANAGER_LOGIN}"

            echo "It's been $hours hours, $minutes minutes, $seconds seconds since #${I_NUM} : ${ISSUE_TITLE} created"


            echo "Sending email to ${ISSUE_USER} about issue: ${ISSUE_TITLE} created at ${created_at} as it's been  $hours hours, $minutes minutes, $seconds seconds since it's created"
            python -c "print('\n\n')"

          done
